# Generated by Django 2.2.3 on 2019-07-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='l_name',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='p_number',
        ),
        migrations.AddField(
            model_name='member',
            name='phone_number',
            field=models.BigIntegerField(default=123456),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(max_length=20),
        ),
    ]
